# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobManagementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('jobTitle', models.CharField(max_length=100, verbose_name='Job Title')),
                ('jobDiscription', djrichtextfield.models.RichTextField(verbose_name='Job Description')),
                ('requiredAnalytics', models.IntegerField(blank=True, null=True, verbose_name='Number of Employee')),
                ('type_of_project', models.CharField(choices=[('One Time Project', 'One Time Project'), ('On going Project', 'On going Project'), ('To be decided', 'To be decided')], default='One Time Project', max_length=50, verbose_name='What type of project you have?')),
                ('payment', models.CharField(choices=[('Pay by Hour', 'Pay by Hour'), ('Pay by Fixed Price', 'Pay by Fixed Price')], default='Pay by Hour', max_length=50, verbose_name='How would you like to pay?')),
                ('duration', models.CharField(choices=[('0-3', '0-3'), ('3-6', '3-6'), ('6-12', '6-12'), ('12+', '12+')], default='0-3', max_length=10, verbose_name='Month')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100, verbose_name='Location')),
            ],
            options={
                'verbose_name_plural': 'Location Name',
            },
        ),
        migrations.CreateModel(
            name='PostJobArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_job_area_of_work', to='app.AreaModel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_area', to='website.JobManagementModel')),
            ],
        ),
        migrations.CreateModel(
            name='PostJobPreferenceLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_preference_language', to='website.JobManagementModel')),
                ('preferenceLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preference_language', to='app.SpeakingLanguageModel')),
            ],
        ),
        migrations.CreateModel(
            name='PostJobPreferenceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_preference_location', to='website.JobManagementModel')),
                ('preferenceLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preference_Location', to='website.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PostJobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_skill', to='website.JobManagementModel')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skills_Required', to='app.ToolsAndLanguageModel')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryPerHour', models.CharField(max_length=100, verbose_name='Salary Per Hour')),
            ],
            options={
                'verbose_name_plural': 'Salary Per Hour',
            },
        ),
        migrations.AddField(
            model_name='jobmanagementmodel',
            name='desiredSalary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_per_hour', to='website.Salary'),
        ),
        migrations.AddField(
            model_name='jobmanagementmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
