# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190625_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmanagementmodel',
            name='desiredSalary',
        ),
        migrations.RemoveField(
            model_name='jobmanagementmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postjobarea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='postjobarea',
            name='job',
        ),
        migrations.RemoveField(
            model_name='postjobpreferencelanguage',
            name='job',
        ),
        migrations.RemoveField(
            model_name='postjobpreferencelanguage',
            name='preferenceLanguage',
        ),
        migrations.RemoveField(
            model_name='postjobpreferencelocation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='postjobpreferencelocation',
            name='preferenceLocation',
        ),
        migrations.RemoveField(
            model_name='postjobskill',
            name='job',
        ),
        migrations.RemoveField(
            model_name='postjobskill',
            name='skills',
        ),
        migrations.DeleteModel(
            name='JobManagementModel',
        ),
        migrations.DeleteModel(
            name='PostJobArea',
        ),
        migrations.DeleteModel(
            name='PostJobPreferenceLanguage',
        ),
        migrations.DeleteModel(
            name='PostJobPreferenceLocation',
        ),
        migrations.DeleteModel(
            name='PostJobSkill',
        ),
    ]
