# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_auto_20190625_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('jobTitle', models.CharField(max_length=100, verbose_name='Job Title')),
                ('jobDiscription', djrichtextfield.models.RichTextField(verbose_name='Job Description')),
                ('requiredAnalytics', models.IntegerField(blank=True, null=True, verbose_name='Number of Employee')),
                ('type_of_project', models.CharField(choices=[('One Time Project', 'One Time Project'), ('On going Project', 'On going Project'), ('To be decided', 'To be decided')], default='One Time Project', max_length=50, verbose_name='What type of project you have?')),
                ('payment', models.CharField(choices=[('Pay by Hour', 'Pay by Hour'), ('Pay by Fixed Price', 'Pay by Fixed Price')], default='Pay by Hour', max_length=50, verbose_name='How would you like to pay?')),
                ('duration', models.CharField(choices=[('0-3', '0-3'), ('3-6', '3-6'), ('6-12', '6-12'), ('12+', '12+')], default='0-3', max_length=10, verbose_name='Month')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('desiredSalary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_per_hour', to='website.Salary')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
