# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('website', '0006_jobmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJobAreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_job_area_of_work', to='app.AreaModel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_area', to='website.JobManagement')),
            ],
        ),
        migrations.CreateModel(
            name='PostJobPreferenceLanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_preference_language', to='website.JobManagement')),
                ('preferenceLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preference_language', to='app.SpeakingLanguageModel')),
            ],
        ),
        migrations.CreateModel(
            name='PostJobPreferenceLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_preference_location', to='website.JobManagement')),
                ('preferenceLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preference_Location', to='website.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PostJobSkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_job_skill', to='website.JobManagement')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skills_Required', to='app.ToolsAndLanguageModel')),
            ],
        ),
    ]
