# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-26 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_userfavouritejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_question', djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='why_should_we_hire_you')),
                ('resume', models.URLField(blank=True, null=True, verbose_name='user_resume')),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_apply', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_job', to='website.JobManagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userfavouritejob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userfavouritejob',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavouriteJob',
        ),
    ]
