# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-27 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190626_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapplyjob',
            options={'verbose_name_plural': 'User Apply Job'},
        ),
    ]
