# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190627_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
    ]
