# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_chatmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
