# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20190629_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmanagement',
            name='approved_employee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numver of approvd employee'),
        ),
    ]
