# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-29 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_jobmanagement_approved_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmanagement',
            name='approved_employee',
            field=models.IntegerField(default=0, verbose_name='Numver of approvd employee'),
        ),
    ]
