# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0017_auto_20190701_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notification Title')),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notification Message')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_job', to='website.JobManagement')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notifcation', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notifcation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "User's Notifications",
            },
        ),
    ]
