# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20190701_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(blank=True, choices=[('User_Applied', 'User_Applied'), ('Company_Approved', 'Company_Approved'), ('Company_Review_Rating', 'Company_Review_Rating'), ('JobSeeker_Review_Rating', 'JobSeeker_Review_Rating')], max_length=200, verbose_name='Type of Notification'),
        ),
    ]
