# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Notification Title'),
        ),
    ]
