# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20190701_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_job', to='website.JobManagement'),
        ),
    ]
