# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0024_auto_20190701_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAndRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('review', djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Review')),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applied_job_completion', to='website.UserApplyJob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Review And Rating',
            },
        ),
    ]
