# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-05 13:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_reviewandrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\\.[a-zA-Z]+$', 'Email must contain at least one @ and .')], verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z-]+$', 'Only character is allowed')], verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-]+$', 'Only character is allowed')], verbose_name='Last Name')),
                ('mobile_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Mobile number must be integer')], verbose_name='Mobile Number')),
                ('message', djrichtextfield.models.RichTextField(verbose_name='message')),
            ],
        ),
        migrations.AlterField(
            model_name='postjobareamodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_job_area', to='website.JobManagement'),
        ),
        migrations.AlterField(
            model_name='postjobpreferencelanguagemodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_job_preference_language', to='website.JobManagement'),
        ),
        migrations.AlterField(
            model_name='postjobpreferencelanguagemodel',
            name='preferenceLanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_language', to='app.SpeakingLanguageModel'),
        ),
        migrations.AlterField(
            model_name='postjobpreferencelocationmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_job_preference_location', to='website.JobManagement'),
        ),
        migrations.AlterField(
            model_name='postjobpreferencelocationmodel',
            name='preferenceLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_Location', to='website.Location'),
        ),
        migrations.AlterField(
            model_name='postjobskillmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_job_skill', to='website.JobManagement'),
        ),
        migrations.AlterField(
            model_name='postjobskillmodel',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_required', to='app.ToolsAndLanguageModel'),
        ),
    ]
