# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20190705_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewandrating',
            old_name='user',
            new_name='receiver_user',
        ),
    ]
