# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-13 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20190713_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
