# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-13 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_userreference_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreference',
            options={'verbose_name_plural': 'Invite User'},
        ),
    ]
