# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-09 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20190713_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmanagement',
            name='approved_employee',
            field=models.IntegerField(default=0, verbose_name='Number of approvd employee'),
        ),
    ]
