# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 10:02
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usereducationmodel_yos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducationmodel',
            name='qualification',
        ),
        migrations.AddField(
            model_name='usereducationmodel',
            name='activity',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Activities and societies'),
        ),
        migrations.AddField(
            model_name='usereducationmodel',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
