# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190704_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='Language Name')),
                ('key', models.CharField(max_length=30, verbose_name='Language Key')),
            ],
            options={
                'verbose_name_plural': 'Language Translation Key',
            },
        ),
    ]
