# Generated by Django 2.1.7 on 2019-06-20 06:33

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
