# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-21 10:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content_management', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Mobile number must be integer')], verbose_name='Mobile Number')),
                ('address', models.CharField(blank=True, max_length=225, null=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\\.[a-zA-Z]+$', 'Email must contain at least one @ and .')], verbose_name='Email')),
            ],
        ),
    ]
